/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type FaqSection = {
  _type: "faqSection";
  note?: string;
};

export type TestimonialsSection = {
  _type: "testimonialsSection";
  note?: string;
};

export type FeaturesSection = {
  _type: "featuresSection";
  features: Array<{
    label: string;
    heading: string;
    description: string;
    imageUrl: string;
    imageAlt?: string;
    imageFirst: boolean;
    imageHasLightBackground: boolean;
    _type: "featureItem";
    _key: string;
  }>;
};

export type AddOnsSection = {
  _type: "addOnsSection";
  addons: Array<{
    title: string;
    description: string;
    iconUrl: string;
    price: string;
    features?: Array<string>;
    _type: "addon";
    _key: string;
  }>;
};

export type CustomerStoriesSection = {
  _type: "customerStoriesSection";
  cards: Array<{
    logoUrl: string;
    imageUrl: string;
    caption: string;
    href: string;
    _type: "storyCard";
    _key: string;
  }>;
};

export type ProductOfferingsSection = {
  _type: "productOfferingsSection";
  offerings: Array<{
    eyebrow: string;
    headline: string;
    body: string;
    ctaLabel?: string;
    ctaHref?: string;
    desktopImageUrl: string;
    mobileImageUrl: string;
    _type: "offering";
    _key: string;
  }>;
};

export type SimpleHeroSection = {
  _type: "simpleHeroSection";
  headline: string;
  subheading: string;
};

export type ProductHeroSection = {
  _type: "productHeroSection";
  headline: string;
  subheading: string;
  primaryButtonLabel?: string;
  primaryButtonHref?: string;
  secondaryButtonLabel?: string;
  secondaryButtonHref?: string;
};

export type HeroSection = {
  _type: "heroSection";
  headline: string;
  subheadingDesktop: string;
  subheadingMobile: string;
  primaryButtonLabel?: string;
  primaryButtonHref?: string;
  secondaryButtonLabel?: string;
  secondaryButtonHref?: string;
};

export type StoriesClosingCard = {
  _id: string;
  _type: "storiesClosingCard";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: string;
  backgroundImageUrl?: string;
  backgroundImageAlt?: string;
  features?: Array<{
    iconUrl?: string;
    text?: string;
    _type: "feature";
    _key: string;
  }>;
  buttonText?: string;
  buttonLink?: string;
};

export type Story = {
  _id: string;
  _type: "story";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projectName: string;
  slug: Slug;
  order?: number;
  storyTitle?: string;
  description?: string;
  backgroundImageUrl?: string;
  backgroundImageAlt?: string;
  websitePreviewUrl?: string;
  websitePreviewAlt?: string;
  buttonText?: string;
  buttonLink?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role?: string;
  quote: string;
  imageUrl?: string;
  imageAlt?: string;
  order?: number;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: string;
  order?: number;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  imageUrl?: string;
  imageAlt?: string;
  publishedAt?: string;
  category?: string;
  externalLink?: string;
  shortDescription?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  metaTitle?: string;
  metaDescription?: string;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  source: string;
  destination: string;
  permanent: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  defaultSeoTitle: string;
  defaultSeoDescription: string;
  defaultOgImage: string;
  organizationName: string;
  organizationLogoUrl: string;
};

export type PricingPlans = {
  _id: string;
  _type: "pricingPlans";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  plans: Array<{
    title: string;
    description: string;
    price: string;
    priceSuffix?: string;
    features?: Array<string>;
    ctaLabel: string;
    ctaHref: string;
    theme: "light" | "dark";
    iconUrls?: Array<string>;
    _type: "plan";
    _key: string;
  }>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  sections: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & ProductHeroSection)
    | ({
        _key: string;
      } & SimpleHeroSection)
    | ({
        _key: string;
      } & ProductOfferingsSection)
    | ({
        _key: string;
      } & CustomerStoriesSection)
    | ({
        _key: string;
      } & AddOnsSection)
    | ({
        _key: string;
      } & FeaturesSection)
    | ({
        _key: string;
      } & TestimonialsSection)
    | ({
        _key: string;
      } & FaqSection)
  >;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | FaqSection
  | TestimonialsSection
  | FeaturesSection
  | AddOnsSection
  | CustomerStoriesSection
  | ProductOfferingsSection
  | SimpleHeroSection
  | ProductHeroSection
  | HeroSection
  | StoriesClosingCard
  | Story
  | Slug
  | Testimonial
  | Faq
  | Post
  | Redirect
  | SiteSettings
  | PricingPlans
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: storiesQuery
// Query: *[_type == "story"] | order(order asc){ projectName, storyTitle, description, backgroundImageUrl, backgroundImageAlt, websitePreviewUrl, websitePreviewAlt, buttonText, buttonLink }
export type StoriesQueryResult = Array<{
  projectName: string;
  storyTitle: string | null;
  description: string | null;
  backgroundImageUrl: string | null;
  backgroundImageAlt: string | null;
  websitePreviewUrl: string | null;
  websitePreviewAlt: string | null;
  buttonText: string | null;
  buttonLink: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: storiesClosingCardQuery
// Query: *[_type == "storiesClosingCard"][0]{ heading, backgroundImageUrl, backgroundImageAlt, features, buttonText, buttonLink }
export type StoriesClosingCardQueryResult = {
  heading: string;
  backgroundImageUrl: string | null;
  backgroundImageAlt: string | null;
  features: Array<{
    iconUrl?: string;
    text?: string;
    _type: "feature";
    _key: string;
  }> | null;
  buttonText: string | null;
  buttonLink: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: faqsQuery
// Query: *[_type == "faq"] | order(order asc){ question, answer }
export type FaqsQueryResult = Array<{
  question: string;
  answer: string;
}>;

// Source: src/sanity/queries.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonial"] | order(order asc){ name, role, quote, imageUrl, imageAlt }
export type TestimonialsQueryResult = Array<{
  name: string;
  role: string | null;
  quote: string;
  imageUrl: string | null;
  imageAlt: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: postsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){    title,    "slug": slug.current,    category,    imageUrl,    imageAlt  }
export type PostsQueryResult = Array<{
  title: string;
  slug: string;
  category: string | null;
  imageUrl: string | null;
  imageAlt: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: postSlugsQuery
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type PostSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: src/sanity/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0]{  title,  imageUrl,  imageAlt,  publishedAt,  category,  externalLink,  shortDescription,  body,  metaTitle,  metaDescription}
export type PostBySlugQueryResult = {
  title: string;
  imageUrl: string | null;
  imageAlt: string | null;
  publishedAt: string | null;
  category: string | null;
  externalLink: string | null;
  shortDescription: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  metaTitle: string | null;
  metaDescription: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: pricingPlansQuery
// Query: *[_type == "pricingPlans"][0]{ plans }
export type PricingPlansQueryResult = {
  plans: Array<{
    title: string;
    description: string;
    price: string;
    priceSuffix?: string;
    features?: Array<string>;
    ctaLabel: string;
    ctaHref: string;
    theme: "dark" | "light";
    iconUrls?: Array<string>;
    _type: "plan";
    _key: string;
  }>;
} | null;

// Source: src/sanity/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0]{    sections[]{      _key,      _type,      _type == "heroSection" => {        headline, subheadingDesktop, subheadingMobile,        primaryButtonLabel, primaryButtonHref,        secondaryButtonLabel, secondaryButtonHref      },      _type == "productHeroSection" => {        headline, subheading,        primaryButtonLabel, primaryButtonHref,        secondaryButtonLabel, secondaryButtonHref      },      _type == "simpleHeroSection" => { headline, subheading },      _type == "productOfferingsSection" => { offerings },      _type == "customerStoriesSection" => { cards },      _type == "addOnsSection" => { addons },      _type == "featuresSection" => { features }    },    seo  }
export type PageBySlugQueryResult = {
  sections: Array<
    | {
        _key: string;
        _type: "addOnsSection";
        addons: Array<{
          title: string;
          description: string;
          iconUrl: string;
          price: string;
          features?: Array<string>;
          _type: "addon";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "customerStoriesSection";
        cards: Array<{
          logoUrl: string;
          imageUrl: string;
          caption: string;
          href: string;
          _type: "storyCard";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "faqSection";
      }
    | {
        _key: string;
        _type: "featuresSection";
        features: Array<{
          label: string;
          heading: string;
          description: string;
          imageUrl: string;
          imageAlt?: string;
          imageFirst: boolean;
          imageHasLightBackground: boolean;
          _type: "featureItem";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "heroSection";
        headline: string;
        subheadingDesktop: string;
        subheadingMobile: string;
        primaryButtonLabel: string | null;
        primaryButtonHref: string | null;
        secondaryButtonLabel: string | null;
        secondaryButtonHref: string | null;
      }
    | {
        _key: string;
        _type: "productHeroSection";
        headline: string;
        subheading: string;
        primaryButtonLabel: string | null;
        primaryButtonHref: string | null;
        secondaryButtonLabel: string | null;
        secondaryButtonHref: string | null;
      }
    | {
        _key: string;
        _type: "productOfferingsSection";
        offerings: Array<{
          eyebrow: string;
          headline: string;
          body: string;
          ctaLabel?: string;
          ctaHref?: string;
          desktopImageUrl: string;
          mobileImageUrl: string;
          _type: "offering";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "simpleHeroSection";
        headline: string;
        subheading: string;
      }
    | {
        _key: string;
        _type: "testimonialsSection";
      }
  >;
  seo: {
    title?: string;
    description?: string;
    ogImage?: string;
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{ siteName, defaultSeoTitle, defaultSeoDescription, defaultOgImage, organizationName, organizationLogoUrl }
export type SiteSettingsQueryResult = {
  siteName: string;
  defaultSeoTitle: string;
  defaultSeoDescription: string;
  defaultOgImage: string;
  organizationName: string;
  organizationLogoUrl: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "story"] | order(order asc){ projectName, storyTitle, description, backgroundImageUrl, backgroundImageAlt, websitePreviewUrl, websitePreviewAlt, buttonText, buttonLink }': StoriesQueryResult;
    '*[_type == "storiesClosingCard"][0]{ heading, backgroundImageUrl, backgroundImageAlt, features, buttonText, buttonLink }': StoriesClosingCardQueryResult;
    '*[_type == "faq"] | order(order asc){ question, answer }': FaqsQueryResult;
    '*[_type == "testimonial"] | order(order asc){ name, role, quote, imageUrl, imageAlt }': TestimonialsQueryResult;
    '*[_type == "post" && defined(slug.current)] | order(publishedAt desc){\n    title,\n    "slug": slug.current,\n    category,\n    imageUrl,\n    imageAlt\n  }': PostsQueryResult;
    '*[_type == "post" && defined(slug.current)]{ "slug": slug.current }': PostSlugsQueryResult;
    '*[_type == "post" && slug.current == $slug][0]{\n  title,\n  imageUrl,\n  imageAlt,\n  publishedAt,\n  category,\n  externalLink,\n  shortDescription,\n  body,\n  metaTitle,\n  metaDescription\n}': PostBySlugQueryResult;
    '*[_type == "pricingPlans"][0]{ plans }': PricingPlansQueryResult;
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    sections[]{\n      _key,\n      _type,\n      _type == "heroSection" => {\n        headline, subheadingDesktop, subheadingMobile,\n        primaryButtonLabel, primaryButtonHref,\n        secondaryButtonLabel, secondaryButtonHref\n      },\n      _type == "productHeroSection" => {\n        headline, subheading,\n        primaryButtonLabel, primaryButtonHref,\n        secondaryButtonLabel, secondaryButtonHref\n      },\n      _type == "simpleHeroSection" => { headline, subheading },\n      _type == "productOfferingsSection" => { offerings },\n      _type == "customerStoriesSection" => { cards },\n      _type == "addOnsSection" => { addons },\n      _type == "featuresSection" => { features }\n    },\n    seo\n  }\n': PageBySlugQueryResult;
    '*[_type == "siteSettings"][0]{ siteName, defaultSeoTitle, defaultSeoDescription, defaultOgImage, organizationName, organizationLogoUrl }': SiteSettingsQueryResult;
  }
}
